import './product.css'

export const metadata = {
  title: "Services",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}
