import './about.css';

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}
