import Image from "next/image";
import Header from "./components/Header";
import Tabs from "./components/Tabs";
import HomeParagraph from "./components/HomeParagraph";
import SlideShow from "./components/SlideShow";
import DescriptionV2 from "./components/DescriptionV2";
import CollaborateChart from "./components/CollaborateChart";
import Faq from "./components/Faq";

export const metadata = {
  title: "Zenith",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Header />
      <Tabs />
      <HomeParagraph />
      <SlideShow />
      <DescriptionV2 />
      <CollaborateChart />
      <Faq />

    </div>
  );
}
